{
 "title": "Airflow cluster Monitoring 2",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "Average Machine Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Pressure",
   "type": "bargauge",
   "description": "Resource pressure via PSI",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "irate(node_pressure_cpu_waiting_seconds_total[$__rate_interval])",
     "legendFormat": "CPU"
    },
    {
     "expr": "irate(node_pressure_memory_waiting_seconds_total[$__rate_interval])",
     "legendFormat": "Mem"
    },
    {
     "expr": "irate(node_pressure_io_waiting_seconds_total[$__rate_interval])",
     "legendFormat": "I/O"
    }
   ]
  },
  {
   "title": "CPU Busy",
   "type": "gauge",
   "description": "Busy state of all CPU cores together",
   "gridPos": { "h": 4, "w": 4, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (1 - avg(rate(node_cpu_seconds_total{mode=\"idle\"}[$__rate_interval])))"
    }
   ]
  },
  {
   "title": "Sys Load",
   "type": "gauge",
   "description": "System load  over all CPU cores together",
   "gridPos": { "h": 4, "w": 4, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "scalar(node_load1) * 100 / count(count(node_cpu_seconds_total) by (cpu))"
    }
   ]
  },
  {
   "title": "RAM Used",
   "type": "gauge",
   "description": "Non available RAM memory",
   "gridPos": { "h": 4, "w": 4, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)) * 100"
    }
   ]
  },
  {
   "title": "SWAP Used",
   "type": "gauge",
   "description": "Used Swap",
   "gridPos": { "h": 4, "w": 4, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(node_memory_SwapTotal_bytes- node_memory_SwapFree_bytes) / (node_memory_SwapTotal_bytes) * 100"
    }
   ]
  },
  {
   "title": "RAM Total",
   "type": "stat",
   "description": "Total RAM",
   "gridPos": { "h": 2, "w": 5, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_memory_MemTotal_bytes" }
   ]
  },
  {
   "title": "SWAP Total",
   "type": "stat",
   "description": "Total SWAP",
   "gridPos": { "h": 2, "w": 5, "x": 19, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_memory_SwapTotal_bytes" }
   ]
  },
  { "title": "Scheduler", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Scheduler heartbeat",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "clamp_max(rate(airflow_scheduler_heartbeat[1m])*6, 1)"
    }
   ]
  },
  {
   "title": "Total successful tasks",
   "type": "stat",
   "description": "Overall task instances successes",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "airflow_dagrun_duration_success_count"
    }
   ]
  },
  { "title": "Executor Pool", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Executor open slots",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "airflow_executor_open_slots" }
   ]
  },
  {
   "title": "Executor running tasks",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "airflow_executor_running_tasks" }
   ]
  },
  {
   "title": "Executor queued tasks",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "airflow_executor_queued_tasks" }
   ]
  },
  { "title": "DAG stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Success DAG run duration",
   "type": "timeseries",
   "description": "Seconds taken for a DagRun to reach success state",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "airflow_dagrun_duration_success",
     "legendFormat": "{{dag_id}} p{{quantile}}"
    }
   ]
  },
  {
   "title": "Failed DAG run duration",
   "type": "timeseries",
   "description": "Seconds taken for a DagRun to reach failed state",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    { "expr": "airflow_dagrun_duration_failed", "legendFormat": "{{dag_id}} p{{quantile}}" }
   ]
  },
  {
   "title": "DAG run dependency check time",
   "type": "timeseries",
   "description": "Seconds taken to check DAG dependencies",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "airflow_dagrun_dependency_check * 1000",
     "legendFormat": "{{dag_id}} p{{quantile}}"
    }
   ]
  },
  {
   "title": "Row title",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 },
   "collapsed": true
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(irate(node_cpu_seconds_total{mode=\"system\"}[$__rate_interval])) / scalar(count(count(node_cpu_seconds_total) by (cpu)))",
     "legendFormat": "System - Processes executing in kernel mode"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{mode=\"user\"}[$__rate_interval])) / scalar(count(count(node_cpu_seconds_total) by (cpu)))",
     "legendFormat": "User - Normal processes executing in user mode"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{mode=\"nice\"}[$__rate_interval])) / scalar(count(count(node_cpu_seconds_total) by (cpu)))",
     "legendFormat": "Nice - Niced processes executing in user mode"
    },
    {
     "expr": "sum by(instance) (irate(node_cpu_seconds_total{mode=\"iowait\"}[$__rate_interval])) / scalar(count(count(node_cpu_seconds_total) by (cpu)))",
     "legendFormat": "Iowait - Waiting for I/O to complete"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{mode=\"irq\"}[$__rate_interval])) / scalar(count(count(node_cpu_seconds_total) by (cpu)))",
     "legendFormat": "Irq - Servicing interrupts"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{mode=\"softirq\"}[$__rate_interval])) / scalar(count(count(node_cpu_seconds_total) by (cpu)))",
     "legendFormat": "Softirq - Servicing softirqs"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{mode=\"steal\"}[$__rate_interval])) / scalar(count(count(node_cpu_seconds_total) by (cpu)))",
     "legendFormat": "Steal - Time spent in other operating systems when running in a virtualized environment"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{mode=\"idle\"}[$__rate_interval])) / scalar(count(count(node_cpu_seconds_total) by (cpu)))",
     "legendFormat": "Idle - Waiting for something to happen"
    }
   ]
  }
 ]
}